# Generated by Django 4.2.4 on 2023-08-24 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle_principal', models.CharField(max_length=100)),
                ('numero_casa', models.CharField(max_length=20)),
                ('calle_transversal', models.CharField(max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.barrio')),
            ],
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('pasaporte', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('parentesco_familiar', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('institucion_trabajo', models.CharField(max_length=100)),
                ('telefono_laboral', models.CharField(blank=True, max_length=20, null=True)),
                ('extension_laboral', models.CharField(blank=True, max_length=10, null=True)),
                ('direccion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.direccion')),
                ('direccion_laboral', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direccion_laboral', to='api.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parroquia')),
            ],
        ),
        migrations.AddField(
            model_name='direccion',
            name='parroquia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.parroquia'),
        ),
        migrations.AddField(
            model_name='direccion',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sector'),
        ),
        migrations.AddField(
            model_name='barrio',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sector'),
        ),
    ]
